routes/web.php
<?php

use App\Http\Controllers\FormController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Module\ItemController;
use App\Http\Controllers\MyController;
use App\Http\Controllers\UserController;
use App\Jobs\TestJob;
use App\Models\Item;
use App\Models\User;
use Illuminate\Support\Facades\Route;
use PhpParser\Node\Expr\Cast\Double;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    // dd(opcache_get_status()['jit']);
    // die;

    $var = "<h1>hello world</h1>";
    $test = 'yes';

    return view('welcome',['var'=> $var , 'test' => $test]);
    return view('welcome',compact('var','test'));
});

Auth::routes();

Route::middleware(['auth'])->group(function(){
    Route::name('staff.')->prefix('module_staff')->middleware(['checkAge'])->group(function(){
        Route::view('testing_page','testing')->name('testing_page_name');

        Route::get('pass/{nric}/parameter',function($nric){
            echo $nric;
        })->name('pass-parameter');
    });

    Route::resource('user',UserController::class);

});





Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::get('route-to-controller/{name}', [HomeController::class,'record'])->name('record');
// Route::get('argument',function(){

// });

// function insert_data(Array $data,String $string ,Double $harga)
// {

// }


Route::get('name_argument', function () {
    $string = 'hello &#47;';
    return htmlspecialchars($string, 'UTF-8', false);
    return htmlspecialchars(string: $string, encoding: 'UTF-8', double_encode: false);

});

Route::get('constructor', function () {
    TestJob::dispatch(5.0,2.0);
});

Route::get('union', function () {
    Class Number{
        public function __construct(
            private int|float $number
        )
        {}
    }
    new Number('NaN');
});



Route::get('null_safe', function () {
  $data = User::find(321312);

//   if($data){
//     echo $data->email;
//   }

    // echo $data ? $data->email : 'null';

    echo $data?->email.'<br>';
    echo optional($data)->email;
});

Route::get('match_expression', function () {
    switch (8.0) {
        case '8.0':
          $result = "Oh no!";
          break;
        case 8.0:
          $result ="This is what I expected";
          break;
      }
      echo $result;


    echo match (8.0) {
        '8.0' => "Oh no!",
        8.0 => "This is what I expected",
      };

 });


Route::get('object_class',function(){
    class conversation{}

    $obj = new conversation;

    $type = '';
    switch (get_class ($obj)) {
        case 'conversation':
        $type = "started_conversation";
        break;

        case "Reply":
        $type = "replied_to_conversation";
        break;

        case 'Comment':
        $type = "commented_on_lesson";
        break;
    }

    // return $type;


    switch ($obj::class) {
        case 'conversation':
        $type = "started_conversation";
        break;

        case "Reply":
        $type = "replied_to_conversation";
        break;

        case 'Comment':
        $type = "commented_on_lesson";
        break;
    }

    return $type;
});

Route::get('new_helper_a',function(){
    $id = 'inv_a1b3243b52z';
    $id2 = 'a1b3243b52z_inv';

    dd(!! preg_match('/_inv$/',$id2) ,  str_ends_with($id2,'_inv'));
    // dd(stripos($id,'inv_')=== 0, str_starts_with($id,'inv_'));



});

Route::get('new_helper_b',function(){
    $url = 'https://example.com?foo=bar';
    dd(strpos($url, '?')  !== false, str_contains($url,'?'));
});

Route::get('model',function(){
    $data = Item::get();
    //select * from items

    $search = 'mobi';
    $data = App\Models\Item::where('item_name','LIKE','%'.$search.'%')->first();
    //select * from items where item_name LIKE %mobi% limit 1

    $data = Item::whereHas('item_description',function($q){
        $q->where('colour','red');
    })->first();

    $data = User::where('name','LIKE','%'.'firdaus'.'%')->first();

    foreach($data->items as $list){
        echo '<br>';
        echo $list?->item_name.'<br>';
        echo $list?->price.'<br>';
        echo optional(optional($list->item_description))->colour.'<br>';
        echo $list?->item_description?->description.'<br>';
        echo '------------------------------------------';
    }
    die;

    // dd($data->item_description->colour.' '.$data->item_description->description);
});

Route::get('form',[FormController::class,'form'])->middleware('auth')->name('form');

Route::post('form-validate',[FormController::class,'store'])->middleware('auth')->name('form-validate');

Route::get('item/index',[ItemController::class,'index'])->middleware('auth')->name('item.index');
Route::get('item/create',[ItemController::class,'create'])->middleware('auth')->name('item.create');
Route::get('item/edit/{id}',[ItemController::class,'edit'])->middleware('auth')->name('item.edit');
Route::post('item/destroy/{id}',[ItemController::class,'destroy'])->middleware('auth')->name('item.destroy');
Route::post('item/store',[ItemController::class,'store'])->middleware('auth')->name('item.store');
Route::post('item/update/{id}',[ItemController::class,'update'])->middleware('auth')->name('item.update');

resources/views/template/app.blade.php
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>@yield('title','Tajuk')</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{{ asset('AdminLTE-master/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('AdminLTE-master/dist/css/adminlte.min.css') }}">
  <!-- SweetAlert 2 -->
  <link rel="stylesheet" href="{{ asset('AdminLTE-master/plugins/sweetalert2/sweetalert2.min.css') }}">
  @stack('css')
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

  <!-- Navbar -->
    @include('template.header')
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="{{ asset('AdminLTE-master/dist/img/AdminLTELogo.png') }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{ asset('AdminLTE-master/dist/img/user2-160x160.jpg') }}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">Alexander Pierce</a>
          <a href="{{ route('logout') }}"
          onclick="event.preventDefault();
                          document.getElementById('logout-form').submit();">
          {{ __('Logout') }}
            </a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                @csrf
            </form>
        </div>

      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      @include('template.menu')
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Starter Page</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Starter Page</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-12">
            <div class="card card-primary card-outline">
              <div class="card-header">
                <h5 class="m-0">@yield('title','Tajuk')</h5>
              </div>
              <div class="card-body">
                @yield('content')
              </div>
            </div>
          </div>
          <!-- /.col-md-6 -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
    <div class="p-3">
      <h5>Title</h5>
      <p>Sidebar content</p>
    </div>
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
 @include('template.footer')
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{{ asset('AdminLTE-master/plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('AdminLTE-master/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('AdminLTE-master/dist/js/adminlte.min.js') }}"></script>
<!-- SweetAlert 2 -->
<script src="{{ asset('AdminLTE-master/plugins/sweetalert2/sweetalert2.min.js') }}"></script>
<script>
    const Toast = Swal.mixin({
    toast: true,
    position: 'top-end',
    showConfirmButton: false,
    timer: 6000,
    timerProgressBar: true,
    didOpen: (toast) => {
        toast.addEventListener('mouseenter', Swal.stopTimer)
        toast.addEventListener('mouseleave', Swal.resumeTimer)
    }
    })

    @if(Session::has('status'))
        Toast.fire({
            icon: "{{ Session::get('status')['type'] ?? 'success' }}",
            title: "{!! Session::get('status')['message'] ?? 'Dialog Message Testing'!!}",
        })
    @endif
</script>
@stack('js')
</body>
</html>

resources/views/template/footer.blade.php
<footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
  </footer>

resources/views/template/header.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{ asset('AdminLTE-master/dist/img/user1-128x128.jpg') }}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{ asset('AdminLTE-master/dist/img/user8-128x128.jpg') }}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{ asset('AdminLTE-master/dist/img/user3-128x128.jpg') }}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>

resources/views/template/menu.blade.php
<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
      <!-- Add icons to the links using the .nav-icon class
           with font-awesome or any other icon font library -->
      <li class="nav-item">
        <a href="#" class="nav-link ">
          <i class="nav-icon fas fa-tachometer-alt"></i>
          <p>
            Route
            <i class="right fas fa-angle-left"></i>
          </p>
        </a>
        <ul class="nav nav-treeview">
          <li class="nav-item">
            <a href="{{ route('staff.testing_page_name') }}" class="nav-link active">
              <i class="far fa-circle nav-icon"></i>
              <p>Testing Page</p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ url('module_staff/testing_page') }}" class="nav-link">
              <i class="far fa-circle nav-icon"></i>
              <p>Testing Page 2</p>
            </a>
          </li>
          <li class="nav-item">
            @php
                $nric = '900821055441';
            @endphp
            <a href="{{ route('staff.pass-parameter',$nric) }}" class="nav-link">
              <i class="far fa-circle nav-icon"></i>
              <p>Pass Parameter</p>
            </a>
          </li>
        </ul>
      </li>
      <li class="nav-item">
        <a href="{{route('record',Auth::user()->name ?? 'Nama')}}" class="nav-link">
          <i class="nav-icon fas fa-th"></i>
          <p>
            Record
            {{-- <span class="right badge badge-danger">New</span> --}}
          </p>
        </a>
      </li>
      <li class="nav-item">
        <a href="{{route('item.index')}}" class="nav-link">
          <i class="nav-icon fas fa-list"></i>
          <p>
            Item
            {{-- <span class="right badge badge-danger">New</span> --}}
          </p>
        </a>
      </li>
    </ul>
  </nav>